In [5]:
import numpy as np
ds = np.array([-2, 6, 3, 10, 15, 48])
# lay 3 15
print(ds[2::2])
# lay 6 10 48
print(ds[1::2])
# lay 10 15 48
print(ds[3:])
# lay 48 15 10
print(ds[-3:])

[ 3 15]
[ 6 10 48]
[10 15 48]
[10 15 48]


In [13]:
import numpy as np
ds = np.array([(-2, 6, 3), (10, 15, 48)])
print(ds)
print(ds.max()) # phan tu lon nhat
print(ds.max(0)) # lon nhat theo cot
print(ds.max(1)) # lon nhat theo hang

[[-2  6  3]
 [10 15 48]]
48
[10 15 48]
[ 6 48]


In [16]:
import math
print("Nhap 2 he so pt bac 1 (ax + b = 0)")
print("Nhap 3 he so pt bac 2 (ax^2 + bx + c = 0)")
r = True
while r:
    ds = list(map(int, input("Nhap he so: ").split()))
    if len(ds) == 2:
        a = ds
        r = False

        if a[0] == 0:
            if a[1] == 0:
                print("PT bac 1 vo so nghiem")
            else:
                print("PT bac 1 vo nghiem")
        else:
            print("PT bac 1 co nghiem la: ", - a[1]/a[0])
    # ----------------------------------------------------        
    elif len(ds) == 3:
        b = ds
        r = False

        # tinh delta
        d = b[1]**2 - 4*b[0]*b[2]

        if d < 0:
            print("PT bac 2 vo nghiem")
        elif d == 0:
            print("PT bac 2 co nghiem kep la: ", - b[1]/(2*b[0]))
        else:
            print("PT bac 2 co 2 nghiem: ")
            n1 = (- b[1] + math.sqrt(d))/(2*b[0])
            n2 = (- b[1] - math.sqrt(d))/(2*b[0])
            print(n1, n2)
    # --------------------------------------------------------
    else:
        print("Khong hop le. Vui long nhap lai")


Nhap 2 he so pt bac 1 (ax + b = 0)
Nhap 3 he so pt bac 2 (ax^2 + bx + c = 0)


Nhap he so:  1 4 2


PT bac 2 co 2 nghiem: 
-0.5857864376269049 -3.414213562373095


In [50]:
import math
x = float(input("Nhap x:"))
print("Cos(x): ")
cos = 0
so = 1 # so thu 1
i = 1
ss = 1e-15
while abs(so) > ss:
    cos += so 
    so *= (-1*x*x)/((2*i) * (2*i-1)) #so thu i
    i += 1
    
print(cos)
print(math.cos(x))

Nhap x: 0.2


Cos(x): 
0.9800665778412416
0.9800665778412416


In [15]:
bang_diem = { 1112233: {'Tin ky thuat': 9.2, 'An toan dien': 8.9, 'The duc': 4.1}, 
              1112244: {'Tin ky thuat': 3.7, 'The duc': 9.0} }
while True:
    a = int(input("Nhap ma sinh vien: "))
    if a not in bang_diem:
        print("Khong tim thay ma sinh vien. Vui long nhap lai!")
    else:
        break

no = False
print("Danh sach mon no:")
for i in bang_diem[a]:
    if bang_diem[a][i] < 5:
        print(i, bang_diem[a][i], sep = ": ")
        no = True
if no == False:
    print("Khong co mon no")

Nhap ma sinh vien:  1112244


Danh sach mon no:
Tin ky thuat: 3.7
